version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "25565:25565"
      - "25575:25575"
    networks:
      - jaunty
    volumes:
      - $HOME/server-data:/data
    environment:
      EULA: "true"
      TZ: "America/New_York"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "3G"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "3G"


networks:
  jaunty:
    external: true
