version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .env
      - server.properties
    ports:
      - "42069:25565"
      - "7091:7091"
      - "25575:25575"
      - "24454:24454/udp"
    networks:
      - jaunty
    volumes:
      - $HOME/server-data:/data
    environment:
      EULA: "true"
      TZ: "America/New_York"
      USE_AIKAR_FLAGS: "true"
      TYPE: "PAPER"
      JMX_HOST: "$HOSTNAME"
      MEMORY: "6G"
      OVERRIDE_SERVER_PROPERTIES: "true"
      FORCE_REDOWNLOAD: "true"
    
networks:
  jaunty:
    external: true
