#!/bin/bash

/usr/bin/docker compose -f /home/mc/server/docker-compose.yml stop

/usr/bin/tar czvf /home/mc/server-backups/jaunty-$(date +"%Y%m%d-%H%M%S").tar.gz /home/mc/server-data/jaunty

/usr/bin/docker compose -f /home/mc/server/docker-compose.yml up -d
