#!/usr/bin/env bash

function log_error() {
    systemd-cat "$0: $@"
}

dependencies=(docker rclone)
for dep in "${dependencies[@]}"; do
    if ! command -v $dep >> /dev/null; then
        log_error "dependency $dep is not installed"
    fi
done

compose_file='/etc/opt/jaunty/minecraft/docker-compose.yml'

docker compose \
    --file $compose_file \
    exec minecraft \
    rcon-cli "say The server is restarting in 1 minute"

sleep 60

docker compose --file $compose_file stop
if (($? > 0)); then
    log_error 'Failed to stop Minecraft server container'
    exit 1
fi

rclone sync /var/opt/jaunty/minecraft jaunty:Jaunty2026
if (($? > 0)); then
    log_error 'Failed to sync data to Backblaze'
    exit 1
fi

docker compose --file $compose_file start
if (($? > 0)); then
    log_error 'Failed to start Minecraft server container'
    exit 1
fi
